---
$schema: "http://json-schema.org/draft-04/schema#"
title: "Bioboxes binning input file validator"
type: "object"
properties:
  version:
    type: "string"
    pattern: "^0.9.\\d+$"
  arguments:
    type: "array"
    minItems: 1
    maxItems: 1
    uniqueItems: true
    items:
      -
        $ref: "#/definitions/fastq"
required:
  - "version"
  - "arguments"
additionalProperties: false
definitions:
  fastq:
    type: "object"
    additionalProperties: false
    required:
      - "fastq"
    properties:
      fastq:
        $ref: "#/definitions/values"
  values:
    type: "object"
    additionalProperties: false
    required:
      - "id"
      - "value"
      - "type"
    properties:
      id: {}
      type: {}
      value: {}
